import type { CaseStudy } from "../../types/case-study";

export const databasesCaseStudy: CaseStudy = {
  id: "databases",
  title: "Database Service Management",
  company: "Chase",
  summary: "A mock interactive case study for explaining service health, ownership, and incident response decisions.",
  role: "Lead Product Designer",
  timeline: "12 weeks",
  flows: [
    {
      id: "dashboard-monitoring",
      title: "Dashboard Monitoring",
      description: "Monitor service health and drill into risk signals before incidents escalate.",
      order: 1,
      initialScreenId: "service-health-overview",
      screens: [
        {
          id: "service-health-overview",
          title: "Service Health Overview",
          componentKey: "databases.serviceHealthOverview",
          actions: [
            {
              id: "view-service-detail",
              label: "View service detail",
              targetScreenId: "service-detail",
            },
          ],
          inspectionPoints: [
            {
              id: "health-status-summary",
              title: "Health Status Summary",
              category: "monitoring",
              x: 18,
              y: 24,
              summary: "Aggregates operational status into a scannable signal for service owners.",
              problem: "Teams had to compare multiple tools to understand whether a database service needed attention.",
              decision: "Surface the health status at the top of the dashboard before secondary metrics.",
              evidence: "Research sessions showed service owners first asked whether anything required immediate action.",
              outcome: "The overview makes triage faster during interview walkthroughs and future prototype testing.",
            },
            {
              id: "risk-trend-chart",
              title: "Risk Trend Chart",
              category: "business-impact",
              x: 62,
              y: 46,
              summary: "Shows how reliability risk changes over time rather than only showing a static score.",
              decision: "Use trend direction to help teams prioritize preventative action.",
              tradeoff: "Trend data adds visual complexity, so the chart stays secondary to the current status.",
            },
            {
              id: "ownership-filter",
              title: "Ownership Filter",
              category: "information-architecture",
              x: 82,
              y: 18,
              summary: "Lets users narrow the dashboard to services they own or support.",
              problem: "Platform teams and app teams needed different slices of the same service inventory.",
              decision: "Keep ownership filtering global so every dashboard module responds consistently.",
            },
          ],
        },
        {
          id: "service-detail",
          title: "Service Detail",
          componentKey: "databases.serviceDetail",
          actions: [
            {
              id: "back-to-overview",
              label: "Back to overview",
              targetScreenId: "service-health-overview",
            },
          ],
          inspectionPoints: [
            {
              id: "dependency-map",
              title: "Dependency Map",
              category: "technical-constraint",
              x: 34,
              y: 38,
              summary: "Visualizes downstream services that may be affected by database events.",
              problem: "Service owners lacked a reliable way to understand blast radius.",
              decision: "Represent dependencies as grouped relationships instead of a dense infrastructure graph.",
              tradeoff: "The simplified map sacrifices low-level topology details for faster comprehension.",
            },
            {
              id: "runbook-link",
              title: "Runbook Link",
              category: "interaction-design",
              x: 74,
              y: 28,
              summary: "Connects service health signals to the next operational action.",
              evidence: "Participants expected dashboard warnings to include a clear path to resolution.",
              outcome: "The prototype can demonstrate how insight turns into action.",
            },
            {
              id: "accessibility-status-label",
              title: "Status Label Pairing",
              category: "accessibility",
              x: 18,
              y: 18,
              summary: "Pairs color-coded states with readable labels for non-color-dependent comprehension.",
              decision: "Use text labels alongside status color so warnings remain understandable across contexts.",
            },
          ],
        },
      ],
    },
    {
      id: "incident-response",
      title: "Incident Response",
      description: "Move from warning signals into incident context and stakeholder communication.",
      order: 2,
      initialScreenId: "incident-list",
      screens: [
        {
          id: "incident-list",
          title: "Incident List",
          componentKey: "databases.incidentList",
          actions: [
            {
              id: "open-incident-detail",
              label: "Open incident detail",
              targetScreenId: "incident-detail",
            },
          ],
          inspectionPoints: [
            {
              id: "severity-sort",
              title: "Severity Sort",
              category: "monitoring",
              x: 24,
              y: 30,
              summary: "Prioritizes incidents by operational severity and customer impact.",
              problem: "Teams needed a fast way to identify which database incidents were most urgent.",
              decision: "Sort active incidents by severity first, then by recency.",
            },
            {
              id: "empty-state-guidance",
              title: "Empty State Guidance",
              category: "interaction-design",
              x: 50,
              y: 66,
              summary: "Uses quiet moments to explain what will appear when no incidents are active.",
              decision: "Make the empty state educational instead of showing a blank table.",
              outcome: "The flow supports normal and no-incident walkthrough scenarios.",
            },
            {
              id: "stakeholder-impact-column",
              title: "Stakeholder Impact Column",
              category: "business-impact",
              x: 78,
              y: 42,
              summary: "Makes the affected business area visible without opening each incident.",
              evidence: "Interview feedback suggested leaders scan for impact before technical details.",
            },
          ],
        },
        {
          id: "incident-detail",
          title: "Incident Detail",
          componentKey: "databases.incidentDetail",
          actions: [
            {
              id: "return-to-incidents",
              label: "Return to incidents",
              targetScreenId: "incident-list",
            },
          ],
          inspectionPoints: [
            {
              id: "timeline-summary",
              title: "Timeline Summary",
              category: "information-architecture",
              x: 32,
              y: 48,
              summary: "Organizes incident events into a chronological narrative for shared context.",
              decision: "Place timeline content near the root-cause summary to support handoffs.",
            },
            {
              id: "owner-assignment",
              title: "Owner Assignment",
              category: "research",
              x: 68,
              y: 24,
              summary: "Clarifies who owns follow-up action during and after an incident.",
              problem: "Participants described ambiguity around accountability after an alert was acknowledged.",
              evidence: "Research notes showed ownership questions came up in every incident-response interview.",
            },
            {
              id: "communication-template",
              title: "Communication Template",
              category: "business-impact",
              x: 76,
              y: 70,
              summary: "Helps teams convert technical incident detail into stakeholder-ready messaging.",
              decision: "Provide a structured update template rather than a free-form text area.",
              tradeoff: "Templates can feel rigid, so the future UI should allow editing before sending.",
            },
          ],
        },
      ],
    },
  ],
};